# Generated by Django 2.2.4 on 2019-11-16 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('baiviet_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('tieude', models.CharField(max_length=300)),
                ('noidung', models.TextField()),
                ('ngay_dang', models.DateTimeField(default=django.utils.timezone.now)),
                ('anhbia', models.CharField(max_length=300)),
            ],
        ),
    ]
